name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间23点01分，北京时间需要+8小时，代表北京时间上午7点01分运行
    - cron: '01 23 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v5
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: Set up Python V3
        uses: actions/setup-python@v3
        with:
            python-version: 3.11.x
            #python-version: '3.11.x' #键值是字符串类型有无引号都是合法的
      - name: install pip packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Push To WeChat
        run: |
          python3 main.py
